version: '3.8'

services:
  server:
    build:
        context: .
        dockerfile: server/Dockerfile
    ports:
        - "5000:5000"


  app:
    build:
        context: app
        dockerfile: Dockerfile
    ports:
        - "80:80"
    depends_on:
        - server