openapi: 3.0.1

info:
  title: MANVSim API
  description: The specification for the API the app uses to communicate with the server.
  version: 0.1.0

paths:

  /{gameId}/{userTan}/patients:
    get:
      summary: Returns a list of patients.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of patients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'

  /{gameId}/{userTan}/patients/{patientId}:
    get:
      summary: Returns a specified patient.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: path
          required: true
          schema:
            type: string
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A patient specified by patientId.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '404':
          description: Patient with patientId could not be found.

  /{gameId}/{userTan}/locations:
    get:
      summary: Returns a list of locations (available to the user).
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'

  /{gameId}/{userTan}/actions:
    get:
      summary: Returns a list of actions available to the user.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of actions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Action'

  /{gameId}/{userTan}/actions/{actionId}:
    post:
      summary: Performs an action.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: path
          required: true
          schema:
            type: string
        - name: actionId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The id of the resulting performed action.
          content:
            application/json:
              schema:
                type: integer

  /{gameId}/{userTan}/actions/result/{performedActionId}:
    get:
      summary: Gets the result of a performed action.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: path
          required: true
          schema:
            type: string
        - name: performedActionId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The result of the performed action.
          content:
            application/json:
              schema:
                type: string

components:
  schemas:

    Patient:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        injuries:
          type: string

    Location:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        resources:
          type: array
          items:
            $ref: '#/components/schemas/Resource'
        locations:
          type: array
          items:
            $ref: '#/components/schemas/Location'

    Resource:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        quantity:
          type: integer

    Action:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        durationInSeconds:
          type: integer
        resourceNamesNeeded:
          type: array
          items:
            type: string