openapi: 3.0.1

info:
  title: MANVSim API
  description: The specification for the API the app uses to communicate with the server.
  version: 0.1.0

paths:

  /{gameId}/patients:
    get:
      summary: Returns a list of patients.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of patients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
              example:
                - id: 1
                  name: Max Mustermann
                  injuries: Beinverletzung
                - id: 2
                  name: Bernd Beispiel
                  injuries: Offene Blutung
                - id: 3
                  name: Patient 3
                  injuries: SHT
                - id: 4
                  name: Ronald Lyons
                  injuries: Bein fehlt

  /{gameId}/patients/{patientId}:
    get:
      summary: Returns a specified patient.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: query
          required: true
          schema:
            type: string
        - name: patientId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A patient specified by patientId.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
              example:
                id: 4
                name: Ronald Lyons
                injuries: Bein fehlt
        '404':
          description: Patient with patientId could not be found.

  /{gameId}/locations:
    get:
      summary: Returns a list of locations (available to the user).
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
              example:
                - id: 1
                  name: Roter Rucksack
                  resources:
                    - id: 1
                      name: Schere
                      quantity: 20
                    - id: 40
                      name: Pflaster
                      quantity: 7
                  locations:
                    - id: 2
                      name: Medikamententasche
                      resources:
                        - id: 2
                          name: Schmerzmittel
                          quantity: 30
                      locations: [ ]
                - id: 3
                  name: RTW
                  resources:
                    - id: 3
                      name: EKG
                      quantity: 120
                  locations:
                    - id: 4
                      name: Medizinschrank
                      resources:
                        - id: 4
                          name: Starkes Schmerzmittel
                          quantity: 50
                      locations: [ ]

  /{gameId}/actions:
    get:
      summary: Returns a list of actions available to the user.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of actions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Action'
              example:
                - id: 1
                  name: Pflaster anbringen
                  durationInSeconds: 10
                  resourceNamesNeeded:
                    - Pflaster
                - id: 2
                  name: Klamotten aufschneiden
                  durationInSeconds: 4
                  resourceNamesNeeded:
                    - Schere
                - id: 3
                  name: Schmerzmittel verabreichen
                  durationInSeconds: 20
                  resourceNamesNeeded:
                    - Schmerzmittel

  /{gameId}/actions/{actionId}:
    post:
      summary: Performs an action.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: query
          required: true
          schema:
            type: string
        - name: actionId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
      responses:
        '200':
          description: The id of the resulting performed action.
          content:
            application/json:
              schema:
                type: integer
              example: 5

  /{gameId}/actions/result/{performedActionId}:
    get:
      summary: Gets the result of a performed action.
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
        - name: userTan
          in: query
          required: true
          schema:
            type: string
        - name: performedActionId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The result of the performed action.
          content:
            application/json:
              schema:
                type: string
              example: Die Maßnahme war erfolgreich.

components:
  schemas:

    Patient:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        injuries:
          type: string

    Location:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        resources:
          type: array
          items:
            $ref: '#/components/schemas/Resource'
        locations:
          type: array
          items:
            $ref: '#/components/schemas/Location'

    Resource:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        quantity:
          type: integer

    Action:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        durationInSeconds:
          type: integer
        resourceNamesNeeded:
          type: array
          items:
            type: string