name: Server Lint & Code Quality
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install pipenv
        working-directory: server
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        working-directory: server
        run: |
          pipenv install

      - name: Run linter
        working-directory: server
        run: |
          pipenv run lint
